apiVersion: v1
kind: Service
metadata:
  name: packet-service
spec:
  type: NodePort
  selector:
    app: packet-inspector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007